### PR TITLE
Complete List of Japanese Terms

### PR DESCRIPTION
**Pull request by KawaneRio**
ja2.

Please discard #18

### CODE REVIEW

**Comment by ryanlo713** [comment]
How about replacing the files under the docs folder with the English version? The English version is newer than the Chinese version.

**Comment by KawaneRio** [comment]
updated

**Comment by KawaneRio** [comment]
wait
build failed. don't merge.

**Comment by ryanlo713** [comment]
now is it fixed?

**Comment by KawaneRio** [comment]
now it is fixed!

**Pull request merged**
